name: 
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: install deps
          run: make install
        - name: run linter
          run: make lint
