name: test-coverage
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest 
    steps:
       - uses: actions/checkout@v2
       - run: make install

       - name: Test & publish code coverage
        - uses: paambaati/codeclimate-action@v3
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
          with:
            coverageCommand: make test-coverage
            debug: true
        - run: NODE_OPTIONS=--experimental-vm-modules npm run test -- --coverage
