name: test-coverage
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest 
    steps:
       - uses: paambaati/codeclimate-action@v2.7.4
       -  env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
       - name: npm install
         run: | 
           make install
       - name: Run tests
         run: |
           NODE_OPTIONS=--experimental-vm-modules npm run test -- --coverage
